JS 課題3 計算機
codeschoolway/js-k3 pull request #1
Opened 2020-03-10 08:31 UTC by codeschoolway

初回

2020-03-11 03:06 UTC, yusaku-inamura requested changes
コメントしました。
また、現在の処理だと

- テキストボックスに数値以外が入力された場合
- そもそもテキストボックスの値が未入力だった場合

に `答えは「NaN」です。` となってしまいますので、上記の場合に計算結果の代わりに `数値を入力してください` と表示するように修正してみましょう。
まずは指摘事項の修正を優先してもらって構いません。

2020-03-11 03:06 UTC, yusaku-inamura commented on main.js
> +    }
このように一つの値に対して複数の条件を羅列する場合は `switch文` の方が可読性が高いことが多いです。
switch文に書き換えてみましょう。

2020-03-11 03:06 UTC, yusaku-inamura commented on main.js
> +    const num1 = parseFloat(document.getElementById("num1").value);
`"num1"` のように文字列リテラルとしてダブルクォーテーションを使用しているようですが、基本的には `シングルクォーテーション(')` を使用することをお勧めします。
jsではどちらを使っても全く意味なのにどうして片方に寄せるのか、と思うかもしれませんが、これはHTMLの属性などで使用できるのがダブルクォーテションのみだからです。
jsは今回のonclickのようにhtml内に埋め込むこともある言語ですので、jsとhtmlで明確に使い分けておいた方が便利なことが多いです。

2020-03-11 03:06 UTC, yusaku-inamura commented on main.js
> +        ).textContent = `答えは「${result}」です。`;
ここは改行入れずに一行で書いてしまっていいと思います。

2020-03-24 03:47 UTC, codeschoolway commented on main.js
> +    }
switch文に書き換えました。

2020-03-24 03:47 UTC, codeschoolway commented on main.js
> +    const num1 = parseFloat(document.getElementById("num1").value);
修正しました。

2020-03-24 03:47 UTC, codeschoolway commented on main.js
> +        ).textContent = `答えは「${result}」です。`;
修正しました。

2020-03-24 03:47 UTC, codeschoolway commented
答えがNaNになる場合に対応しました。

2020-03-24 04:03 UTC, Yuzunoha commented on main.js
> +    const res = button.id;
定数名 `res` が何の値かわかりにくいので改善しましょう。
 `buttonId` とかでよいです。
もしくは一箇所でしか使っていないので定数に代入しなくてもよいですね。

2020-03-24 04:04 UTC, Yuzunoha commented on main.js
> +    if(isNaN(num1) || isNaN(num2)) {
せっかくなので「0で割ることはできません」というガードも実装しましょう

2020-03-24 04:58 UTC, codeschoolway commented on main.js
> +    const res = button.id;
定数に代入しない方法にしました。

2020-03-24 04:58 UTC, codeschoolway commented on main.js
> +    if(isNaN(num1) || isNaN(num2)) {
修正しました。

2020-03-24 05:20 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-03-24 05:53 UTC, merged